# Generated by Django 4.2.23 on 2025-06-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('time_published', models.DateTimeField()),
                ('authors', models.JSONField(blank=True, null=True)),
                ('summary', models.TextField()),
                ('banner_image', models.URLField(blank=True, null=True)),
                ('source', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('overall_sentiment_score', models.FloatField()),
                ('overall_sentiment_label', models.CharField(max_length=50)),
                ('topics', models.JSONField(blank=True, null=True)),
                ('ticker_sentiment', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
