# Generated by Django 5.0.6 on 2025-06-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopGainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('change_amount', models.FloatField()),
                ('change_percentage', models.CharField(max_length=10)),
                ('volume', models.IntegerField()),
            ],
        ),
    ]
