# Generated by Django 5.0.6 on 2025-06-23 20:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0002_topgainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='topgainer',
            name='last_updated',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='topgainer',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_api.ticker'),
        ),
        migrations.AlterUniqueTogether(
            name='topgainer',
            unique_together={('ticker', 'last_updated')},
        ),
        migrations.CreateModel(
            name='TopLoser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('change_amount', models.FloatField()),
                ('change_percentage', models.CharField(max_length=10)),
                ('volume', models.IntegerField()),
                ('last_updated', models.DateField(default=datetime.date.today)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_api.ticker')),
            ],
            options={
                'unique_together': {('ticker', 'last_updated')},
            },
        ),
    ]
