# Generated by Django 4.2.23 on 2025-06-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0003_ticker_topgainer_last_updated_alter_topgainer_ticker_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticker',
            old_name='name',
            new_name='longname',
        ),
        migrations.AddField(
            model_name='ticker',
            name='fullExchangeName',
            field=models.CharField(default='UNKNOWN', max_length=10),
        ),
        migrations.AddField(
            model_name='ticker',
            name='headquarters',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
        migrations.AddField(
            model_name='ticker',
            name='industry',
            field=models.CharField(blank=True, default='UNKNOWN', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='market_cap',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='sector',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
        migrations.AddField(
            model_name='ticker',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
