# Generated by Django 4.2.23 on 2025-06-24 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0004_rename_name_ticker_longname_ticker_fullexchangename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticleTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_score', models.FloatField()),
                ('relevance_score', models.FloatField()),
                ('sentiment_label', models.CharField(max_length=50)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_api.newsarticle')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_api.ticker')),
            ],
        ),
    ]
