# Generated by Django 4.2.23 on 2025-06-24 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0006_remove_ticker_fullexchangename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticker',
            old_name='longname',
            new_name='name',
        ),
    ]
