# Generated by Django 4.2.23 on 2025-06-26 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0007_rename_longname_ticker_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='ticker_sentiment',
        ),
        migrations.CreateModel(
            name='NewsArticleTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_api.newsarticle')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_api.topic')),
            ],
        ),
    ]
