# Generated by Django 4.2.23 on 2025-06-26 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0008_topic_remove_newsarticle_ticker_sentiment_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='newsarticletopic',
            unique_together={('article', 'topic')},
        ),
    ]
