# Generated by Django 4.2.23 on 2025-06-26 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0009_alter_newsarticletopic_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='topics',
        ),
    ]
