# Generated by Django 4.2.23 on 2025-06-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0010_remove_newsarticle_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topgainer',
            name='last_updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='toploser',
            name='last_updated',
            field=models.DateTimeField(),
        ),
    ]
