# Generated by Django 4.2.23 on 2025-06-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0011_alter_topgainer_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topgainer',
            name='last_updated',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='toploser',
            name='last_updated',
            field=models.DateField(),
        ),
    ]
